version: 1.0

seed: 0

model:
    cnn: "i3d"
    train_entire_cnn: True
    in_channel: 1024
    n_features: 256
    n_classes: 2
    n_stages: 4
    n_layers: 10

dataset:
    train_annot_file_path: "/home/ubuntu/slocal/PitchDetection/json/train_annotations250108.json"
    val_annot_file_path: "/home/ubuntu/slocal/PitchDetection/json/val_annotations250108.json"
    test_annot_file_path: "/home/ubuntu/slocal/PitchDetection/json/test_annotations.json"
    clip_length: 512
    frame_root_dir: "/home/ubuntu/slocal/PitchDetection/data/frames"

training:
    epochs: 100
    batch_size: 2
    num_workers: 2
    step_size: 10
    gamma: 0.8
    lr: 0.001
    log_dir: "log/"
    save_interval: 10
    log_interval: 20
    gpu_ids: [0]

testing:
    batch_size: 1
    num_workers: 1
